### PR TITLE
Add New Discords

### PR DESCRIPTION
**Pull request by jimender2**
Add Discords to DC614, DC937, and Control Things.

### CODE REVIEW

**Comment by INIT6Source** [comment]
Ready to add Control Things and formatting! I removed DC(G)s from this list as it was duplicating https://github.com/DefconParrot/DefconGroups

**Comment by INIT6Source** [comment]
Added the changes; Thanks! 

Sorry, wasn't sure if there was a way to accept half the commits in a PR while rejecting the others so I closed the PR and added the changes myself. Let me know if there was a way to do that though!

**Comment by INIT6Source** [comment]
Realized I could have left the PR open and asked you to make changes; Apologies!

**Comment by jimender2** [comment]
Cherry picking also works too.
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests
https://docs.github.com/en/desktop/managing-commits/cherry-picking-a-commit-in-github-desktop

**Pull request closed without merging**
